/* JS FUNCTIONS FOR CONSTITUTION */

$(document).ready(function() {
    $('.header-selectable').click(function() {
        var elementId = $(this).attr('id');
        handleSpecialClick(elementId);
    });
});

function handleSpecialClick(elementId) {
    let annotationText = ''; // Variable to store the annotation text
    switch (elementId) {
        case 'pre':
            annotationText = '<h1>The Preamble</h1>The preamble summarizes the goals the Constitution is trying to accomplish. The Constitution aims to fix the problems with the <a href="./history.html">Articles of Confederacy</a>, and make sure to establish a equal democracy.';
            break;
        case 'art1':
            annotationText = '<h1>Article 1</h1><h3>Section 1 Summary</h3>\nLegislative powers of the U.S. are given to the Senate and the House of Representatives.\n\n<h3>Section 2 Summary</h3>\nRepresentatives are elected every two years and represent each state; they must be 25+ years old, have been a citizen of the U.S. for 7+ years, and live in the state they are running for. A proportional number of representatives and taxes are given to each state with respect to their population. The House of Representatives chooses their speaker and officers and has to power to impeach. If a position opens up for a representative in a state, it is up to the governor of that state to host an election to fill the empty position.\n\n'
            + '<h3>Section 3 Summary</h3>\nTwo senators are chosen to represent each state every six years; their elections are spaced out within the six years, however, to allow ⅓ of the senate to be replaced every 2 years. If a vacancy opens up, the governor of that state is responsible for temporarily filling the position with someone else until another person is actually chosen for the position. To be eligible to be a senator, one must be 30+ years old, have been a citizen for 9+ years, and live in the state they are running for. The Vice President of the U.S. is the President of the Senate but only votes if a tiebreaker vote is needed. The Senate chooses its officers and a “President Pro Tempore” to serve if the Vice President is unavailable. The Senate can hold impeachment trials.\n\n'
            + '<h3>Section 4 Summary</h3>\nThe House & Senate election procedures are outlined by each state\'s individual legislatures.\n\n<h3>Section 5 Summary</h3>\nEach chamber of the legislative branch functions independently with its guidelines on how it will operate properly. A majority must be present in either chamber to do official business.\n\n<h3>Section 6 Summary</h3>\nAll legislators are paid an amount that is determined by law and given out by the Treasurer of the United States. They also cannot be arrested while in session in Congress (with exceptions for severe cases) - this will allow them to complete their responsibilities without such interruptions. Members of Congress also cannot hold two positions in different branches. This helps to ensure the separation of governmental powers.\n\n'
            + '<h3>Section 7 Summary</h3>\nRevenue bills must start in the House. Every bill that successfully makes it through the 2 chambers of Congress must then be approved by the President. The President can veto and have the original chamber reconsider their bill and cast another (⅔ majority) vote in both chambers. If it is approved after all that, it can be signed into law. Alternatively, if the president doesn\'t take action within 10 days of receiving the bill, it will automatically become law.\n\n'
            + '<h3>Section 8 Summary</h3>\nCongress\'s important powers: create and collect taxes; borrow the U.S.\'s money; facilitate trade with foreign countries and Native American tribes; give money its value; designate post offices and roads; deal with piracies and felonies; declare war; maintain support for the army and navy; exercise laws over the District of Columbia and all other owned lands; and make all laws necessary for the proper functioning of the U.S.\n\n<h3>Section 9 Summary</h3>\nSlavery could not be prohibited until after 1808, however, a $10 tax could be placed on any individuals who brought a slave into the nation. No state\'s exports can be taxed by the government. Additionally, the government will not have preferences for one state\'s (trading) ports over another\'s. Congress can only spend money that they are allowed to use by the Treasury. No government official can claim a title or gift from a foreign nation without Congressional backing.\n\n'
            + '<h3>Section 10 Summary</h3>\nStates cannot take the role of Congress and independently make decisions that go against nationwide values.\n\n<h3>Annotations</h3>\nPrior to the 17th Amendment, the Senate was put in place by other U.S. legislative officials. The Founding Fathers originally set up the country this way because they felt that those already in governmental positions would have a better feel for who would make a good senator, and they would be able to choose more qualified candidates; they also felt it would serve as a good balance people\'s power and governmental power, seeing as though the people would get to vote for the Representatives and the government would get to have a say on the Senators. While this may sound like sound reasoning, it appears to be flawed - the government has a say on who gets elected to the government. This decision ultimately takes choice away from the people, and could lead to decisions being made that benefit the government over the people. More on this amendment later.\n\nThe President\'s power to veto is mentioned in section 7. This shows the check and balance considerations the Framers had in mind while they were planning the Constitution; the President (executive branch) is forced to come to a compromise with Congress (legislative branch). Thus, no one branch has too much authority over the bills that get accepted into law. While the judicial branch does not have the ability to make and pass laws in agreement with the other branches, the Supreme Court gets to decide on whether passed laws are constitutional or not. TLDR, bill tasks are divided amongst the government.'
            + '<br><br><br><br><br><br>';
        break;
            case 'art2':
            annotationText = "<h1>Article 2</h1>" +
            "<h3>Section 1 Summary</h3>\nSection 1 of Article Two introduces the role of the vice president and the president. One term for both of them is 4 years. A president picks their vice president, while the president is elected through the Electoral College. In the electoral college, each state has a number represented by the number of representatives the state has in Congress. If the Electoral College votes ends up in a tie, Congress votes to break the tie. To be President of the United States, you must be a native born US citizen, be at least 35 years old, and live in the US for at least 14 years." +
            "\n\n<h3>Section 2 Summary</h3>\nSection 2 of Article Two describes the president's powers, such as the ability to pardon people, the ability to control the US military, the ability to appoint judges and public officials, and the ability to make recess appointments to fill vacancies that occur when the Senate is in recess. The president can also make treaties with the approval of two-thirds of the Senate. The president can make a Cabinet of experts to help them make decisions." +
            "\n\n<h3>Section 3 Summary</h3>\nSection 3 of Article Two states that the president must convene both houses of Congress, interact with foreign representatives, and appoint federal officers. The president must give a state of union and the President is allowed to make executive orders, which can share the same properties of legislative law." +
            "\n\n<h3>Section 4 Summary</h3>Section 4 of Article Two describes the impeachment process. A president can be impeached for treason, bribery, or other high crimes and misdemeanors. Two-Thirds of Congress must agree to impeach the president, causing them to immediately end their term.";
            break;
        case 'art3':
            annotationText = '<h1>Article 3</h1>' +
            "<h3>Section 1 Summary</h3>\n Section 1 of Article 3 introduces the role of the Judicial branch, which is made up of the Supreme Court and the Inferior Courts. Federal judges do not have term limits and the salary of a federal judge cannot be changed." +
            "\n\n<h3>Section 2 Summary</h3>\nSection 2 of Article 3 describes the judicial branch's powers. Federal judiciaries can go over the Constitution, federal laws, federal treaties, controversies between states and foreign powers, and other things given to the branch. The Supreme Court's rulings have higher precedence than lower court rulings. Lower court rulings can be appealed and looked over by the Supreme Court. This process is called judicial review." +
            "\n\n<h3>Section 3 Summary</h3>\nSection 3 of Article 3 defines what counts as treason under federal law and how the court can persecute it. The court needs at least two witnesses to testify to the treason or the accused to plead guilty to treason. The power to punish those who commit treason goes to Congress. " +
            "\n\n<h3>Annotations</h3>\nDue to ambiguity within this article, a lot of how the Judicial Branch functions today were decided upon by legislative acts and the Supreme Court’s rulings. Here are just a few of the ambiguities that cases and legislation ruled upon to make the Judicial Branch what it is today." +
            "\n\n<h3>The size of the Supreme Court</h3>\nYou may have thought that the number of Justices on the Supreme Court has always been nine but, as Article 3 does not specify the size of the court, this has not always been so. The first bill introduced in the United States Senate became the Judiciary Act of 1789, which divided the country into fourteen judicial districts and three circuits. In this bill, the size of the Supreme Court was set to six, with one Chief Justice and five Associate Justices. However, the number of Justices on the Court changed six times before settling at nine in 1869."+
            "\n\n<h3>Judicial Review</h3>\nJudicial review is the power of the courts to examine the actions of all branches of government and to determine whether they are consistent with the constitution. Any actions judged inconsistent are deemed unconstitutional and are then null and void. This power the Supreme Court holds was established by John Marshall, the fourth chief justice of the court. In the 1803 case Marbury v. Madison, Marshall ruled that the Supreme Court had the power to invalidate legislation enacted by Congress. However, there is nothing in the text of the constitution that states that the Court has this power. The success of the power of judicial review rests on the Supreme Court’s own ruling, plus the lack of effective political challenges to it at the time." +
            "\n\n<h3>Defining “Good Behavior”</h3><p>Section 1 specifies that federal judges hold their offices “during good behavior.” This standard was borrowed from English law and ensures that judges hold their seats for life. But what defines \“good behavior\" exactly? This has been a subject of debate; in particular, whether there is a distinct standard for removal apart from the “high crimes and misdemeanors” standard that other federal officials can be impeached for. There has not been a definitive answer to this question, however, historical English legal precedent can help us understand what the authors of the constitution were referring to.</p>"+
            "<p>As previously mentioned, the term “good behavior” was borrowed from English law, but so was its intended legal meaning. Prior to 1701, the tenure of Judges in England was determined by the Crown which often reserved the right to remove them. This means that judges in England were able to be removed for the Crown’s political or personal gain, allowing an avenue for potential corruption. In 1701 Parliament passed legislation that barred the Crown from removing judges as long as they served with “good behavior.” This law was then mirrored in many American colonies’ constitutions.</p>" +
            "<p>The Framers of the constitution put the “good behavior” clause in for similar reasons to its English predecessor: to protect the judiciary branch against the risk of other branches seeking to expand its power. Rather than being influenced by the Congress or the President, the judges’ seats and salaries for life are meant to ensure that the Judiciary would not succumb to political pressure and remain unbiased.</p><br><br>";
            break;
        case 'art4':
            annotationText = '<h1>Article 4</h1><h3>Article 4 Summary</h3>\nArticle IV of the U.S. Constitution focuses on the relationship between the states, their obligations, and the relationship between the states and the federal government. Despite the diversity of state governments, it helps to ensure that the United States functions as a single nation by outlining fundamental principles that support uniformity and fairness across state lines.\n'
                            + '<h3>Section 1 Summary</h3>States must honor the laws, court decisions, and records of other states, and Congress has the power to determine how this recognition should occur and set rules for how states cooperate on legal matters.\n'
                            + '<h3>Section 2 Summary</h3>Citizens of one state are entitled to the same privileges and protections as citizens of any other state. States cannot discriminate against citizens of other states in terms of basic rights.'
                            + '<p>If someone commits a crime in one state and flees to another, the second state must return the person to the state where the crime was committed (extradition)</p>'
                            + '<p>Fugitive Slave Clause required that escaped enslaved individuals be returned to their enslavers, even if they fled to a free state.</p>'
                            + '<h3>Section 3 Summary</h3>Congress has the power to admit new states into the Union, but no new state can be created from the land of an existing state without the consent of both the affected state and Congress.'
                            + '<p>Congress has authority over federal territories and properties, such as national parks, military bases, and unincorporated territories.</p>'
                            + '<h3>Section 4 Summary</h3>Republican Government: The federal government guarantees each state a republican form of government, meaning a government in which the people elect representatives.'
                            + '<p>Protection: The federal government is obligated to protect states from foreign invasions and, upon request from state authorities, help in situations of domestic unrest or violence.</p>'
                            + '<h3>Annotation</h3><u>Full Faith and Credit Clause</u>'
                            + '<p>The Full Faith and Credit Clause ensures that legal decisions, contracts, and public records in one state are recognized and honored in other states. For example, a marriage, court judgment, or driver\'s license from one state must be accepted in another. Without the Clause, interstate cooperation would be thrown into disarray, and people could lose rights or obligations as soon as they cross state lines.</p>'
                            + '<p><u>Privileges and Immunities Clause & Extradition</p></u>'
                            + '<p>The Privileges and Immunities Clause guarantees out-of-state residents the same rights and anti-discrimination safeguards as those who live in their home states. At the same time, the Extradition Clause ensures that criminal suspects cannot escape punishment by fleeing to another state, and that states can request that suspects be returned for trial. Today, the Privileges and Immunities Clause still protects out-of-state residents from discrimination. For example, while states can charge out-of-state students higher tuition rates, they cannot separately tax residents of other states. It also plays a significant role in law enforcement, ensuring that criminals cannot avoid prosecution by crossing state lines.</p>'
                            + '<p><u>Admission of New States and Management of Territories</p></u>'
                            + '<p>This section lays out the process by which new states can be added to the Union. Congress has the authority to admit new states but splitting or combination of states requires consent from both Congress and the affected states. Additionally, as the federal government oversees U.S. territories, it can administer resources and territory that are not a part of any state. There is debate over whether U.S. territories like Puerto Rico and Washington, D.C. should be granted full statehood, and this section is pertinent to those discussions. It also calls into question the authority and management of US territories as well as the way their citizens engage in federal decision-making.</p>'
                            + '<p><u>Republican Form of Government and Protection</p></u>'
                            + '<p>The clause guarantees a republican, or representative, government for the states. Besides that, it requires the federal government to defend the states against foreign invasion and to assist state governments in resolving internal disputes. This clause is still applicable in the case of domestic abuse even though the federal government\'s duty to defend states against invasion has decreased. States are entitled to request federal assistance, including the National Guard\'s deployment, in the event of civil unrest. Moreover, it is also used in cases where state authorities ask the federal government to step in and help control disturbances or keep the peace in circumstances like the civil rights movement. In order to maintain state democracy and federal accountability, the republican clause is still applicable in the modern form of government.</p>'
                            + '<br><br><br>';
            break;
        case 'art5':
            annotationText = "<h1>Article 5</h1>Article Five describes the amendment process. Two-Thirds of Congress or Two-Thirds of the 50 states can propose amendment. When Three-Fourths of Congress or the States agree on the amendment, and as long as it doesn't affect Article 1, it will be added to the Constitution.";
            break;
        case 'art6':
            annotationText = '<h1>Article 6</h1>Article Six allows Congress to be responsible for any debts earned from the Articles of Confederation. It also makes the United States law the law of the land, and prevents mandatory religious tests for running for a government position.';
            break;
        case 'art7':
            annotationText = '<h1>Article 7</h1>Article Seven recounts each state delegate signing and putting the Constitution into Affect.';
            break;
        case 'am1':
            annotationText = '<h1>First Amendment</h1>The government cannot do anything to restrict freedom of speech and expression, freedom of religion, freedom of the press, and freedom to protest. \n\nThis amendment is the reason why people are free to practice whatever religion they want and share their own thoughts and opinions. It also makes sense that this is the First Amendment, seeing as though the founders sought freedom from Great Britain, and these are some of the ways in which they wanted to distinguish themselves.';
            break;
        case 'am2':
            annotationText = '<h1>Second Amendment</h1>People will not have to worry about their access to guns being taken away. Additionally, the U.S. strives to operate a calculated, skillful military. Amendment 2 primarily serves as a reaffirmation of how people can be protected from danger in the U.S. People can opt for more or less gun control - as is often debated - but guns are never going to go away due to this amendment (unless, of course, another amendment was made).';
            break;
        case 'am3':
            annotationText = '<h1>Third Amendment</h1>Soldiers cannot be forcibly placed into someone\'s home while they are not serving at war. This amendment soothes peoples\' anxieties about having to host their homes for militiamen they don\'t know anything about - if anything was to happen, the homeowner\'s consent would be required. While this may not seem like that big of a worry today - hence, why the Third Amendment is rarely mentioned now - the worry that sparked the Third Amendment was once a very real situation Colonists had to deal with in Britain. The Quartering Act of 1765 was one of the Intolerable Acts that inevitably pushed Colonists to fight for their independence.';
            break;
        case 'am4':
            annotationText = '<h1>Fourth Amendment</h1>The government cannot go through with a search of someone\'s personal property without probable cause and a warrant clearly detailing the nature of the search - what item(s) will be searched, for what reason the search is being conducted, etc. \n\nThis amendment prevents government abuse of power by protecting people\'s personal privacy regarding their possessions. It would feel very invasive to have to let government officials go through your belongings whenever they please under any circumstances without sufficient reason.';
            break;
        case 'am5':
            annotationText = '<h1>Fifth Amendment</h1>People have the right to remain silent in trials (excluding a Grand Jury) to prevent incrimination of themselves. They also cannot be tried and punished twice for the same situation. A person also does not have to worry about the unfair loss of their natural rights during a trial. Lastly, the government cannot take someone\'s private property without giving them an adequate trade.\n\nWithout this amendment, people could abuse the judicial system by repeatedly incriminating others for the same crime. This amendment also relates to what happens if the government ever needs to take the land your house/road/etc. is on; you will not have to worry about losing your property without notice or reimbursement.';
            break;
        case 'am6':
            annotationText = '<h1>Sixth Amendment</h1>If someone is being brought to court, they have the right to have their trial in their state, within a reasonable amount of time after the accusation. They will be given information about how they were accused and who is against them. They are also guaranteed a defendant and a jury.\n\nThis amendment is important in ensuring trials are fair, and goes along with the United States\' motto of "guilty until proven innocent," allowing everyone to have an unbiased, objective trial. If those who were accused of a crime were given unfair court treatment, they would always be assumed to be at fault and could be wrongly convicted simply due to the nature of the circumstances they were put in, in the courtroom. In reality, the person assumed to be at fault could also be innocent.';
            break;
        case 'am7':
            annotationText = "<h1>Seventh Amendment</h1>" + 
            "<p>The 7th Amendment was ratified in 1791. It protects the right for citizens to have a jury trial in federal courts with civil cases where the claim exceeds twenty dollars. It also prohibits judges in these trials from overruling facts the jury reveals. </p>" + 
            "<p>During the Constitutional Convention, civil juries were hotly contested. The Federalists were concerned that the states’ civil juries' problem of constantly defending debtors would carry to federal civil juries and essentially nullify laws of contract. The Anti-Federalists saw civil juries as an effective defense of overreach and corruption from the branches of the federal government.</p>";
            break;
        case 'am8':
            annotationText = '<h1>Eighth Amendment</h1><p>The 8th Amendment was ratified in 1791. It forbids the use of excessive bails or fines in criminal trials, as well as punishments determined to be “cruel and unusual.”</p>' + 
            '<p>Fun fact: The initial version of the Constitution actually did not include this phrase. It was only after critics voiced their concern for the potential abuse of power the government could perform by inflicting humiliating or cruel punishments on their citizens.</p>';
            break;
        case 'am9':
            annotationText = '<h1>Ninth Amendment</h1><p>The 9th Amendment was ratified in 1791. It clarifies that the Constitution is not a comprehensive list of every right of citizens, and that future righteous are entitled to protection by the law. </p>' +
            '<p>This Amendment has been argued and interpreted in different ways. Some argued that the “enumerated rights” refer to the “collective rights” of the citizens, while others have said that it encapsulates all possible rights expressed or implied by the Constitution, Declaration of Independence and other bills of rights and declarations.</p>' + 
            '<p>One important Supreme Court case where these two opposing interpretations came up was the legalization of birth control in Griswold v. Connecticut (1965.) The concurring opinion said that the right to personal privacy is implicit, but not explicitly stated in the 4th Amendment and that as an implicit right, it comes under the protection of the 9th Amendment. The dissenting camp disagreed, saying that the 9th Amendment has nothing to do with its case and that the Amendment’s original purpose was to state that all powers not delegated to the federal government were those of the people and the states.</p>';
            break;
        case 'am10':
            annotationText = "<h1>Tenth Amendment</h1><p>The 10th Amendment was ratified in 1791. It makes it clear that the powers that aren't specifically given to the federal government or withheld from states, are for the states and the people of the USA.</p>" + 
            "<p>The 9th and 10th Amendments are quite similar and raise similar issues of what is or is not a right. It has been interpreted that the 10th Amendment is a clarification of the federal government being limited and that a government decision shouldnt be investigated as an infringement of civil liberties, but as an overreach of its power.<p>" + 
            "<p>Two important Supreme court decisions that invoked the 10th Amendment are:<li>Cooper v. Aaron (1958) that determined that Arkansas cannot delay the desegregation of schools.</li><li>United States v. Alfonso D. Lopez, Jr. (1995) determined that federal established “gun-free zones” on public school campuses were unconstitutional</li></p>";
            break;
        case 'am11':
            annotationText = '<h1>Eleventh Amendment</h1><p>The 11th Amendment was ratified in 1795. It establishes that states are immune from lawsuits from out-of-state citizens and foreign individuals. The states also do not have to hear lawsuits filed against them when the charges are based on federal law. </p>' + 
            '<p>An interesting modern development regarding this amendment is Alden v. Maine in 1999, which determined that states are immune from federal-based lawsuits inside state courts and that states can opt to hear such lawsuits if they want to.</p>';
            break;
        case 'am12':
            annotationText = '<h1>Twelfth Amendment</h1><p>The 12th Amendment was ratified in 1804. It outlines the procedure of how Presidents and Vice Presidents are elected, making it so they are elected together. Previously, the President was the candidate who received the most electoral votes and the runner up was Vice President. This meant that they were from different parties. which made governance difficult. This Amendment allows each party to nominate their President and Vice President together so they will appear on the ballot together. It also extends the eligibility requirements to become president to the vice president.</p><p>The 12th Amendment also strongly implies that the President and Vice President should not be from the same state. Although it does not disqualify a Vice President who is from the same state as the President, it disqualifies the electors from that state from voting for both offices. </p><p>The 12th Amendment establishes how to handle selecting the President when neither candidate got the majority vote of the electors: the House of Representatives selects the new president from the top three candidates. The votes in the House would be by state in this scenario as not to have larger states’ opinions outweigh smaller ones.</p>';
            break;
        case 'am13':
            annotationText = '<h1>Thirteenth Amendment</h1>The 13th Amendment is one of the most important amendments in U.S. history. Ratified in 1865, it abolished slavery and involuntary servitude, except as punishment for a crime.'
                           + '<p>Abolition of Slavery is officially ended slavery in the United States, marked a fundamental shift in American society, ensuring that no one could be legally held as a slave, it laid the foundation for further civil rights advancements. However, the exception for "punishment for crime" created a legal loophole that has been debated and criticized, especially regarding the prison labor system.</p>'
                           + '<p>The clause allowing involuntary servitude as punishment for a crime has led to the use of prison labor, which some critics argue is a modern form of slavery. Today, this issue is central in debates about criminal justice reform, mass incarceration, and prison labor practices.</p>'
                           + '<p>The 13th Amendment also gives Congress the authority to pass laws to uphold the 13th Amendment. Over time, Congress used this power to pass civil rights legislation aimed at dismantling remnants of slavery and racial discrimination.</p>';
            break;
        case 'am14':
            annotationText = '<h1>Fourteenth Amendment</h1>The 14th Amendment, ratified in 1868, is a cornerstone of civil rights in the U.S. It addresses citizenship, equal protection under the law, and due process.'
                           + '<p>Several significant provisions found in the U.S. Constitution\'s 14th Amendment are still vital to contemporary society. The Citizenship Clause ends the debate over black citizenship and grants citizenship to everyone born or naturalized in the country. The Due Process Clause forbids states from taking arbitrary action against citizens and mandates that people\'s "life, liberty, or property" be safeguarded through just trials. Contrarily, the Equal Protection Clause mandates that states guarantee equal protection to all individuals, establishing the legal foundation for advancements in civil rights such as desegregation, the defense of women\'s rights, and the rights of LGBTQ+ people.</p>'
                           + '<p>The representation in Amendment 14 was designed to penalize states that did not allow Black men to vote by lowering their congressional representation. Even though it was not successfully implemented, it set the stage for upcoming safeguards for the right to vote. This section continues to inform discussions about voting rights, gerrymandering, and voter suppression while highlighting the significance of equitable representation in government. Voter disenfranchisement principles, though originally focused on Black male voters, are largely applicable to any group that is currently denied the right to vote, underscoring continuous efforts to guarantee equitable access to the voting process.</p>'
                           + '<p>Disqualification from office was designed to prevent former Confederates from holding office after the Civil War. It ensures that individuals who violate their allegiance to the U.S. cannot serve in government unless forgiven by Congress.(In the aftermath of events like the January 6th attack on the Capitol, this section has been cited in discussions about whether certain individuals should be disqualified from holding office.)</p>'
                           + '<p>Public Debt clause made it clear that Confederate debts would not be recognized while simultaneously guaranteeing that obligations owed by the US government, particularly those incurred during the Civil War, must be honored. In discussions concerning the federal debt ceiling, this clause is occasionally brought up to make sure the United States pays its debts in full and avoids default.</p>'
                           + '<p>The 14th Amendment authorizes Congress to pass laws to ensure that the principles of the 14th Amendment are upheld. It was used to pass civil rights laws to ensure protection from discrimination. Today, the clause authorizes Congress to enact laws such as the Civil Rights Act, the Voting Rights Act, and others designed to combat discrimination and promote equality. In addition to offering continuous protection, this type of authorization allows Congress to continue addressing contemporary forms of inequality like voting rights violations, gender inequality, and racial discrimination.</p>'
                           + '<br><br><br>';
            break;
        case 'am15':
            annotationText = '<h1>Fifteenth Amendment</h1>The 15th Amendment, which forbade racial discrimination in voting and was ratified in 1870, is an important piece of legislation that gave African American men the right to vote. Although there were numerous obstacles in the way of its implementation, it represented a major advancement toward racial equality in the US.'
                           + '<p>The 15th Amendment explicitly prohibits the federal and state governments from denying citizens the right to vote based on race, color, or former slave status. This was a direct response to discriminatory practices that existed prior to the Civil War and the abolition of slavery.</p>'
                           + '<p>Most representatively, the bill was designed to protect the voting rights of African Americans. However, despite the Amendment\'s promise, many Southern states continued to use literacy tests, poll taxes, and violence to prevent blacks from voting, and it wasn\'t until the Voting Rights Act of 1965 that many of these issues were addressed. And today, the amendment remains relevant in the ongoing struggle against voter suppression tactics such as voter ID laws, gerrymandering, and purging of voter rolls.</p>'
                           + '<p>Section 2 of the 15th Amendment grants Congress the power to pass laws to enforce the right to vote, regardless of race. Discussions concerning how to maintain the efficacy of the 15th Amendment\'s protections have arisen in the wake of the Supreme Court\'s 2013 ruling in Shelby County v. Holder, which undermined certain provisions of the Voting Rights Act.</p>';
            break;
        case 'am16':
            annotationText = '<h1>Sixteenth Amendment</h1>The 16th Amendment, ratified in 1913, gave Congress the power to impose an income tax without the need to apportion it among the states or base it on the U.S. Census. The result of the amendment led to a fundamental change in the way the federal government taxed and the creation of a stable and progressive tax system.'
                           + '<p>Prior to the 16th Amendment, the federal government relied primarily on tariffs and excise taxes, which tended to be regressive and disproportionately affected low-income people. The federal income tax was considered a fairer form of taxation that taxed individuals based on their ability to pay. The Supreme Court had ruled in Pollock v. Farmers\' Loan & Trust Co. (1895) that the property income tax was unconstitutional because it had to be apportioned on a per capita basis. The 16th Amendment bypassed this ruling and allowed the government to impose a national income tax without regard to the population of each state.</p>'
                           + '<p>Instead, these federal income taxes are a major source of federal revenue, funding vital services such as defense, infrastructure, social security, education, and health care programs.</p>';
            break;
        case 'am17':
            annotationText = '<h1>Seventeenth Amendment</h1>The 17th Amendment, ratified in 1913, changed the way U.S. senators were elected by introducing a system of direct election of senators by the people rather than by state legislatures. The purpose was to make the government more democratic and accountable to the public.'
                           + '<p>Before the 17th Amendment, U.S. Senators were elected by state legislatures, which often led to corruption and lack of accountability. For example, political elites and wealthy interest groups could directly influence state legislatures to elect senators who favored their interests. With the official release of this amendment, the people can be allowed to vote for their senators. This amendment shifted power to the people, increasing government transparency and public control over government.'
                           + '<p>In addition to changing the way the U.S. Senate is elected; this section allows flexibility in filling Senate vacancies. If a senator leaves office, the governor of that state can appoint a temporary replacement until a special election is held. This ensures the state\'s representation in the Senate while giving the people the opportunity to elect a permanent replacement.';
            break;
        case 'am18':
            annotationText = '<h1>Eighteenth Amendment</h1>The 18th Amendment prohibited the manufacture, sale, and transportation of alcoholic beverages, especially spirituous liquors, in the United States. The amendment marked the beginning of the Prohibition Era, a social experiment aimed at reducing crime, improving public morals, and promoting health.'
                           + '<p>The 18th Amendment was driven by the temperance movement, which advocated the elimination of alcohol consumption, arguing that it would reduce crime, break up families, and improve the moral fabric of society. The amendment did not outlaw the consumption of alcohol, but rather the production, sale and transportation of alcohol. However, this attempt to legislate morality led to many unintended consequences, including the rise of illegal alcohol production and sale, speakeasies, and organized crime.</p>'
                           + '<p>Prohibition can be characterized as a massive expansion of old-time federal power over personal choice and economic activity. Today, we continue to debate the role of government in regulating substances such as marijuana, cigarettes, and e-cigarette products.</p>'
                           + '<p>In the text, “The Congress and the several States shall have concurrent power to enforce this article by appropriate legislation.” Congress and the states were given permission to enforce prohibition laws under this provision. However, the growing illegal liquor market and general disdain for the law made it very difficult to enforce the amendment.</p>';
            break;
        case 'am19':
            annotationText = "<h1>Nineteenth Amendment</h1>The 19th Amendment granted women the right to vote in the United States, marking a significant expansion of democratic rights. It prohibited any U.S. citizen from being denied the right to vote on the basis of sex. This amendment was the result of decades of activism by women's suffrage advocates, culminating in a landmark victory for gender equality and enfranchisement in American democracy.";
            break;
        case 'am20':
            annotationText = "<h1>Twentieth Amendment</h1>The 20th Amendment, often referred to as the 'Lame Duck Amendment,' changed the dates for the beginning and ending of the terms of the president, vice president, and members of Congress. It moved the start of the presidential and congressional terms from March to January, thereby  shortening the 'lame duck' period, during which outgoing officials remained in power after an election but before the new officials took office.";
            break;
        case 'am21':
            annotationText = "<h1>Twenty-first Amendment</h1>The 21st Amendment repealed the 18th Amendment, effectively ending the national prohibition of alcohol in the United States. This amendment was passed in response to the significant rise in organized crime, corruption, and public discontent associated with Prohibition. The 21st Amendment also granted individual states the authority to regulate alcohol sales within their own borders.";
            break;
        case 'am22':
            annotationText = "<h1>Twenty-second Amendment</h1>The 22nd Amendment limited the number of terms a president could serve to two. This amendment was enacted after Franklin D. Roosevelt was elected to four terms, breaking the precedent set by George Washington of serving only two terms. The 22nd Amendment ensures that no individual can hold the office of the president for more than two elected terms, thereby reinforcing democratic principles and preventing any potential for presidential overreach or a move towards authoritarianism.";
            break;
        case 'am23':
            annotationText = "<h1>Twenty-third Amendment</h1>The 23rd Amendment granted residents of Washington, D.C. the right to vote in presidential elections by allocating them a number of electors in the Electoral College equal to the number they would have if they were a state, but no more than the least populous state. This amendment gave the citizens of the nation\'s capital, who previously had no vote in presidential elections, a voice in choosing the president and vice president.";
            break;
        case 'am24':
            annotationText = "<h1>Twenty-fourth Amendment</h1>The 24th Amendment abolished poll taxes in federal elections, which had been used in many Southern states to disenfranchise African American voters and other marginalized groups. By eliminating this economic barrier, the  amendment helped to enforce the principle that voting rights should not be  dependent on a person\'s financial status, promoting greater inclusivity and equity in the democratic process.";
            break;
        case 'am25':
            annotationText = "<h1>Twenty-fifth Amendment</h1>The 25th Amendment clarified the procedures for presidential succession and the filling of vice-presidential vacancies, as well as the process for dealing with presidential disabilities. It allows the vice president to become acting president if the president is unable to perform the duties of the office, providing a clear constitutional procedure for maintaining continuity and stability in the executive branch during times of crisis or incapacity.";
            break;
        case 'am26':
            annotationText = "<h1>Twenty-sixth Amendment</h1>The 26th Amendment lowered the voting age from 21 to 18, reflecting the argument that if 18-year-olds could be drafted to fight in wars, they should also have the right to vote. This change expanded the electorate and empowered millions of young Americans to participate in the democratic process, particularly during the Vietnam War era.";
            break;
        case 'am27':
            annotationText = "<h1>Twenty-seventh Amendment</h1>The 27th Amendment prevents any law that changes the compensation of members of Congress from taking effect until after the next election of representatives. Originally proposed in 1789 as part of the original Bill of Rights, it was not ratified until over 200 years later. This amendment aims to prevent conflicts of interest by ensuring that lawmakers cannot immediately benefit from pay raises they vote for themselves, promoting accountability and fairness in government.";
            break;
        default:
            annotationText = 'Unknown element clicked!';
    }

    // Output the annotation text to the annotation box
    document.getElementById('annotations').innerHTML = annotationText;
}


